import {useEffect,useMemo,useState,type FormEvent} from "react";
import {login,changePassword} from "../api/auth.api";
import {get} from "../api/client";
import {myExams,myAttempts,notifications,markNotificationRead} from "../api/portal.api";
import {students,teachers,departments,exams} from "../api/management.api";
import type {Role,Student,Teacher,Department,Exam,Notification,LoginResponse} from "../types";

function Login({onLogin}:{onLogin:(x:LoginResponse)=>void}){
 const [username,setUsername]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setError("");setBusy(true);try{onLogin(await login(username,password))}catch(e){setError(e instanceof Error?e.message:"Login failed")}finally{setBusy(false)}}
 return <main className="auth"><form className="card auth-card" onSubmit={submit}><h1>MFT</h1><p>سامانه مدیریت آموزشی</p><label>نام کاربری<input value={username} onChange={e=>setUsername(e.target.value)} required autoComplete="username"/></label><label>رمز عبور<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="current-password"/></label>{error&&<div className="error">{error}</div>}<button disabled={busy}>{busy?"در حال ورود...":"ورود"}</button></form></main>;
}
function ChangePassword({onDone}:{onDone:()=>void}){const [c,setC]=useState(""),[n,setN]=useState(""),[e,setE]=useState("");async function go(x:React.FormEvent){x.preventDefault();setE("");try{await changePassword(c,n);onDone()}catch(e){setE(e instanceof Error?e.message:"خطا")}}return <main className="auth"><form className="card auth-card" onSubmit={go}><h2>تغییر رمز عبور</h2><label>رمز فعلی<input type="password" value={c} onChange={e=>setC(e.target.value)} required/></label><label>رمز جدید<input type="password" minLength={8} value={n} onChange={e=>setN(e.target.value)} required/></label>{e&&<div className="error">{e}</div>}<button>ذخیره</button></form></main>}
function Table({title,rows}:{title:string;rows:Array<Record<string,unknown>>}){return <section className="card"><h2>{title}</h2>{rows.length===0?<p className="muted">داده‌ای وجود ندارد.</p>:<div className="table-wrap"><table><thead><tr>{Object.keys(rows[0]).map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{Object.values(r).map((v,j)=><td key={j}>{String(v??"-")}</td>)}</tr>)}</tbody></table></div>}</section>}
function Dashboard({role}:{role:Role}){const [data,setData]=useState<any>();const [error,setError]=useState("");useEffect(()=>{get("/dashboard").then(setData).catch(e=>setError(e.message))},[]);return <><header><h1>داشبورد</h1><span>{role}</span></header>{error&&<div className="error">{error}</div>}<div className="grid">{["students","teachers","departments","questions","exams"].map(k=><div className="card stat" key={k}><strong>{data?.[k]??"—"}</strong><span>{k}</span></div>)}</div></>}
function StudentPortal(){const [es,setEs]=useState<any[]>([]),[as,setAs]=useState<any[]>([]),[ns,setNs]=useState<Notification[]>([]),[err,setErr]=useState("");async function load(){try{const [e,a,n]=await Promise.all([myExams(),myAttempts(),notifications()]);setEs(e);setAs(a);setNs(n)}catch(e){setErr(e instanceof Error?e.message:"خطا")}}useEffect(()=>{load()},[]);return <><header><h1>پرتال دانشجو</h1></header>{err&&<div className="error">{err}</div>}<Table title="آزمون‌های من" rows={es.map(e=>({عنوان:e.title,مدت:e.durationMinutes,وضعیت:e.attempted?"انجام شده":"آماده",تعداد_سوال:e.questionCount}))}/><Table title="سوابق آزمون" rows={as.map(a=>({آزمون:a.examTitle,شروع:a.startedAt,ارسال:a.submittedAt??"—",نمره:a.score??"—"}))}/><section className="card"><h2>اعلان‌ها</h2>{ns.map(n=><article className={n.isRead?"notice read":"notice"} key={n.id}><b>{n.title}</b><p>{n.message}</p>{!n.isRead&&<button onClick={async()=>{await markNotificationRead(n.id);load()}}>خوانده شد</button>}</article>)}</section></>}
function Management({role}:{role:Role}){const [tab,setTab]=useState("students");const [rows,setRows]=useState<any[]>([]),[error,setError]=useState("");useEffect(()=>{setError("");const f=tab==="students"?students():tab==="teachers"?teachers():tab==="departments"?departments():exams();f.then(setRows).catch(e=>setError(e.message))},[tab]);return <><header><h1>مدیریت</h1><span>{role}</span></header><nav className="tabs">{["students","teachers","departments","exams"].map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav>{error&&<div className="error">{error}</div>}<Table title={tab} rows={rows.map(x=>Object.fromEntries(Object.entries(x).slice(0,7)))}/></>}
function App(){const [user,setUser]=useState<LoginResponse|null>(()=>{try{return JSON.parse(localStorage.getItem("mft_user")||"null")}catch{return null}});const [page,setPage]=useState("dashboard");const role=user?.role;const logout=()=>{localStorage.clear();setUser(null)};if(!user)return <Login onLogin={x=>{localStorage.setItem("mft_token",x.token);localStorage.setItem("mft_user",JSON.stringify(x));setUser(x)}}/>;if(user.mustChangePassword)return <ChangePassword onDone={()=>{const u={...user,mustChangePassword:false};localStorage.setItem("mft_user",JSON.stringify(u));setUser(u)}}/>;const isStudent=role==="Student";const nav=useMemo(()=>isStudent?["dashboard","portal"]:["dashboard","management"],[isStudent]);return <div className="shell"><aside><h2>MFT</h2>{nav.map(x=><button className={page===x?"active":""} onClick={()=>setPage(x)} key={x}>{x==="dashboard"?"داشبورد":"مدیریت / پرتال"}</button>)}<button onClick={logout}>خروج</button></aside><main className="content">{page==="dashboard"?<Dashboard role={role!}/> :isStudent?<StudentPortal/>:<Management role={role!}/>}</main></div>}
export default App;