using Microsoft.EntityFrameworkCore;
using System.Security.Cryptography;
using Mft.Application.Abstractions;
using Mft.Application.Contracts;
using Mft.Domain;
namespace Mft.Application.Services;
public sealed class MftService(IMftDbContext db,ICurrentUser current,ISmsSender sms):IMftService {
 async Task<Guid?> ScopeAsync(Guid? requested,CancellationToken ct){
  if(current.Role==UserRole.SuperAdmin) return requested;
  var scope=current.Role==UserRole.Department
   ? await db.Users.Where(x=>x.Id==current.UserId).Select(x=>x.DepartmentId).SingleOrDefaultAsync(ct)
   : current.Role==UserRole.Teacher
    ? await db.Teachers.Where(x=>x.UserId==current.UserId).Select(x=>(Guid?)x.DepartmentId).SingleOrDefaultAsync(ct)
    : await db.Students.Where(x=>x.UserId==current.UserId).Select(x=>(Guid?)x.DepartmentId).SingleOrDefaultAsync(ct);
  if(scope is null) throw new UnauthorizedAccessException("No department scope is assigned.");
  if(requested.HasValue && requested.Value!=scope.Value) throw new UnauthorizedAccessException("You cannot access another department.");
  return scope;
 }
 async Task EnsureTargetDepartment(Guid departmentId,CancellationToken ct){var scope=await ScopeAsync(departmentId,ct);if(scope.HasValue&&scope.Value!=departmentId)throw new UnauthorizedAccessException("Department access denied.");}
 static string TempPassword(){const string chars="ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789";var a=new char[10];for(var i=0;i<a.Length;i++)a[i]=chars[RandomNumberGenerator.GetInt32(chars.Length)];return new string(a);}
 public async Task<IReadOnlyList<StudentDto>> StudentsAsync(string? s,Guid? d,CancellationToken ct){
  if(current.Role==UserRole.Student){return await db.Students.AsNoTracking().Include(x=>x.User).Include(x=>x.Department).Where(x=>x.UserId==current.UserId).Select(x=>new StudentDto(x.Id,x.User.FullName,x.StudentNumber,x.Department.Name,x.Department.DegreeLevel,x.GPA,x.Status)).ToListAsync(ct);}
  var scope=await ScopeAsync(d,ct);var q=db.Students.AsNoTracking().Include(x=>x.User).Include(x=>x.Department).AsQueryable();if(!string.IsNullOrWhiteSpace(s))q=q.Where(x=>x.User.FullName.Contains(s)||x.StudentNumber.Contains(s));if(scope.HasValue)q=q.Where(x=>x.DepartmentId==scope);return await q.Select(x=>new StudentDto(x.Id,x.User.FullName,x.StudentNumber,x.Department.Name,x.Department.DegreeLevel,x.GPA,x.Status)).ToListAsync(ct);
 }
 public async Task<StudentDto> CreateStudentAsync(CreateStudentRequest r,CancellationToken ct){
  if(current.Role is not (UserRole.SuperAdmin or UserRole.Department or UserRole.Teacher)) throw new UnauthorizedAccessException();
  await EnsureTargetDepartment(r.DepartmentId,ct);
  var password=TempPassword();var u=new User{Id=Guid.NewGuid(),Username=r.Username,PasswordHash=BCrypt.Net.BCrypt.HashPassword(password),FullName=r.FullName,Email=r.Email,Mobile=r.Mobile,Role=UserRole.Student,MustChangePassword=true,DepartmentId=r.DepartmentId,CreatedAt=DateTime.UtcNow};
  var s=new Student{Id=Guid.NewGuid(),UserId=u.Id,DepartmentId=r.DepartmentId,StudentNumber=r.StudentNumber,EntryYear=r.EntryYear,GPA=r.GPA,Status=r.Status,User=u};db.Users.Add(u);db.Students.Add(s);await db.SaveChangesAsync(ct);
  await sms.SendAsync(r.Mobile,$"حساب دانشجویی شما ایجاد شد. نام کاربری: {r.Username} | رمز موقت: {password} | در اولین ورود رمز را تغییر دهید.",ct);
  var d=await db.Departments.FindAsync([r.DepartmentId],ct);return new(s.Id,r.FullName,r.StudentNumber,d?.Name??"",d?.DegreeLevel??"",r.GPA,r.Status);
 }
 public async Task DeleteStudentAsync(Guid id,CancellationToken ct){if(current.Role is not (UserRole.SuperAdmin or UserRole.Department or UserRole.Teacher))throw new UnauthorizedAccessException();var s=await db.Students.Include(x=>x.User).SingleOrDefaultAsync(x=>x.Id==id,ct)??throw new KeyNotFoundException();await EnsureTargetDepartment(s.DepartmentId,ct);db.Students.Remove(s);db.Users.Remove(s.User);await db.SaveChangesAsync(ct);}
 public async Task<IReadOnlyList<TeacherDto>> TeachersAsync(string? s,Guid? d,CancellationToken ct){if(current.Role==UserRole.Student)throw new UnauthorizedAccessException();var scope=await ScopeAsync(d,ct);var q=db.Teachers.AsNoTracking().Include(x=>x.User).Include(x=>x.Department).AsQueryable();if(!string.IsNullOrWhiteSpace(s))q=q.Where(x=>x.User.FullName.Contains(s)||x.Specialty.Contains(s));if(scope.HasValue)q=q.Where(x=>x.DepartmentId==scope);return await q.Select(x=>new TeacherDto(x.Id,x.User.FullName,x.Department.Name,x.Specialty,x.Status)).ToListAsync(ct);}
 public async Task<TeacherDto> CreateTeacherAsync(CreateTeacherRequest r,CancellationToken ct){if(current.Role is not (UserRole.SuperAdmin or UserRole.Department))throw new UnauthorizedAccessException();await EnsureTargetDepartment(r.DepartmentId,ct);var u=new User{Id=Guid.NewGuid(),Username=r.Username,PasswordHash=BCrypt.Net.BCrypt.HashPassword(r.Password),FullName=r.FullName,Email=r.Email,Mobile=r.Mobile,Role=UserRole.Teacher,DepartmentId=r.DepartmentId,CreatedAt=DateTime.UtcNow};var t=new Teacher{Id=Guid.NewGuid(),UserId=u.Id,DepartmentId=r.DepartmentId,Specialty=r.Specialty,Status=r.Status,User=u};db.Users.Add(u);db.Teachers.Add(t);await db.SaveChangesAsync(ct);var d=await db.Departments.FindAsync([r.DepartmentId],ct);return new(t.Id,r.FullName,d?.Name??"",r.Specialty,r.Status);}
 public async Task CreateDepartmentManagerAsync(CreateDepartmentManagerRequest r,CancellationToken ct){if(current.Role!=UserRole.SuperAdmin)throw new UnauthorizedAccessException();var d=await db.Departments.FindAsync([r.DepartmentId],ct)??throw new KeyNotFoundException();var u=new User{Id=Guid.NewGuid(),Username=r.Username,PasswordHash=BCrypt.Net.BCrypt.HashPassword(r.Password),FullName=r.FullName,Email=r.Email,Mobile=r.Mobile,Role=UserRole.Department,DepartmentId=d.Id,CreatedAt=DateTime.UtcNow};db.Users.Add(u);d.ManagerName=r.FullName;await db.SaveChangesAsync(ct);}
 public async Task<IReadOnlyList<DepartmentDto>> DepartmentsAsync(CancellationToken ct){if(current.Role!=UserRole.SuperAdmin)throw new UnauthorizedAccessException();return await db.Departments.AsNoTracking().Select(d=>new DepartmentDto(d.Id,d.Name,d.ManagerName,d.DegreeLevel,d.IsActive,d.Students.Count,d.Teachers.Count)).ToListAsync(ct);}
 public async Task<DepartmentDto> CreateDepartmentAsync(CreateDepartmentRequest r,CancellationToken ct){if(current.Role!=UserRole.SuperAdmin)throw new UnauthorizedAccessException();var d=new Department{Id=Guid.NewGuid(),Name=r.Name,ManagerName=r.ManagerName,DegreeLevel=r.DegreeLevel};db.Departments.Add(d);await db.SaveChangesAsync(ct);return new(d.Id,d.Name,d.ManagerName,d.DegreeLevel,true,0,0);}
 public async Task DeleteDepartmentAsync(Guid id,CancellationToken ct){if(current.Role!=UserRole.SuperAdmin)throw new UnauthorizedAccessException();var d=await db.Departments.FindAsync([id],ct)??throw new KeyNotFoundException();db.Departments.Remove(d);await db.SaveChangesAsync(ct);}
 public async Task<IReadOnlyList<QuestionDto>> QuestionsAsync(Guid? d,CancellationToken ct){if(current.Role==UserRole.Student)throw new UnauthorizedAccessException();var scope=await ScopeAsync(d,ct);var q=db.Questions.AsNoTracking().Include(x=>x.Department).Include(x=>x.CreatedByTeacher).ThenInclude(x=>x.User).Include(x=>x.Options).AsQueryable();if(scope.HasValue)q=q.Where(x=>x.DepartmentId==scope);return await q.Select(x=>new QuestionDto(x.Id,x.Text,x.Type,x.Points,x.Department.Name,x.CreatedByTeacher.User.FullName,x.Options.Select(o=>new QuestionOptionDto(o.Id,o.Text,o.IsCorrect)).ToList())).ToListAsync(ct);}
 public async Task<QuestionDto> CreateQuestionAsync(CreateQuestionRequest r,CancellationToken ct){if(current.Role is not (UserRole.SuperAdmin or UserRole.Teacher))throw new UnauthorizedAccessException();await EnsureTargetDepartment(r.DepartmentId,ct);var teacher=await db.Teachers.SingleOrDefaultAsync(x=>x.Id==r.TeacherId,ct)??throw new KeyNotFoundException();if(current.Role==UserRole.Teacher&&teacher.UserId!=current.UserId)throw new UnauthorizedAccessException();var q=new Question{Id=Guid.NewGuid(),DepartmentId=r.DepartmentId,CreatedByTeacherId=r.TeacherId,Text=r.Text,Type=r.Type,Points=r.Points,Options=r.Options.Select(o=>new QuestionOption{Id=Guid.NewGuid(),Text=o.Text,IsCorrect=o.IsCorrect}).ToList()};db.Questions.Add(q);await db.SaveChangesAsync(ct);var x=await db.Questions.Include(a=>a.Department).Include(a=>a.CreatedByTeacher).ThenInclude(a=>a.User).Include(a=>a.Options).SingleAsync(a=>a.Id==q.Id,ct);return new(x.Id,x.Text,x.Type,x.Points,x.Department.Name,x.CreatedByTeacher.User.FullName,x.Options.Select(o=>new QuestionOptionDto(o.Id,o.Text,o.IsCorrect)).ToList());}
 public async Task<IReadOnlyList<ExamDto>> ExamsAsync(CancellationToken ct){if(current.Role==UserRole.Student)throw new UnauthorizedAccessException();var scope=await ScopeAsync(null,ct);var q=db.Exams.AsNoTracking().Include(x=>x.Department).Include(x=>x.Teacher).ThenInclude(x=>x.User).AsQueryable();if(scope.HasValue)q=q.Where(x=>x.DepartmentId==scope);return await q.Select(x=>new ExamDto(x.Id,x.Title,x.Department.Name,x.Teacher.User.FullName,x.DurationMinutes,x.PassingScore,x.ScheduledAt,x.Status,x.Questions.Count)).ToListAsync(ct);}
 public async Task<ExamDto> CreateExamAsync(CreateExamRequest r,CancellationToken ct){if(current.Role is not (UserRole.SuperAdmin or UserRole.Teacher))throw new UnauthorizedAccessException();await EnsureTargetDepartment(r.DepartmentId,ct);var teacher=await db.Teachers.SingleOrDefaultAsync(x=>x.Id==r.TeacherId,ct)??throw new KeyNotFoundException();if(current.Role==UserRole.Teacher&&teacher.UserId!=current.UserId)throw new UnauthorizedAccessException();var e=new Exam{Id=Guid.NewGuid(),DepartmentId=r.DepartmentId,TeacherId=r.TeacherId,Title=r.Title,DurationMinutes=r.DurationMinutes,PassingScore=r.PassingScore,ScheduledAt=r.ScheduledAt,AllowNavigation=r.AllowNavigation,Status=ExamStatus.Published};e.Questions=r.QuestionIds.Select((id,i)=>new ExamQuestion{ExamId=e.Id,QuestionId=id,SortOrder=i+1}).ToList();db.Exams.Add(e);await db.SaveChangesAsync(ct);return (await ExamsAsync(ct)).First(x=>x.Id==e.Id);}
 public async Task<object> DashboardAsync(CancellationToken ct){var scope=await ScopeAsync(null,ct);var students=db.Students.AsQueryable();var teachers=db.Teachers.AsQueryable();var questions=db.Questions.AsQueryable();var exams=db.Exams.AsQueryable();if(scope.HasValue){students=students.Where(x=>x.DepartmentId==scope);teachers=teachers.Where(x=>x.DepartmentId==scope);questions=questions.Where(x=>x.DepartmentId==scope);exams=exams.Where(x=>x.DepartmentId==scope);}return new{students=await students.CountAsync(ct),teachers=await teachers.CountAsync(ct),departments=current.Role==UserRole.SuperAdmin?await db.Departments.CountAsync(ct):1,questions=await questions.CountAsync(ct),exams=await exams.CountAsync(ct)};}
}