using Microsoft.EntityFrameworkCore; using Mft.Application.Abstractions; using Mft.Application.Contracts; using Mft.Domain;
namespace Mft.Application.Services;
public sealed class MftService(IMftDbContext db):IMftService {
public async Task<IReadOnlyList<StudentDto>> StudentsAsync(string? s,Guid? d,CancellationToken ct){var q=db.Students.AsNoTracking().Include(x=>x.User).Include(x=>x.Department).AsQueryable();if(!string.IsNullOrWhiteSpace(s))q=q.Where(x=>x.User.FullName.Contains(s)||x.StudentNumber.Contains(s));if(d.HasValue)q=q.Where(x=>x.DepartmentId==d);return await q.Select(x=>new StudentDto(x.Id,x.User.FullName,x.StudentNumber,x.Department.Name,x.Department.DegreeLevel,x.GPA,x.Status)).ToListAsync(ct);}
public async Task<StudentDto> CreateStudentAsync(CreateStudentRequest r,CancellationToken ct){var u=new User{Id=Guid.NewGuid(),Username=r.Username,PasswordHash=BCrypt.Net.BCrypt.HashPassword(r.Password),FullName=r.FullName,Email=r.Email,Role=UserRole.Student,CreatedAt=DateTime.UtcNow};var s=new Student{Id=Guid.NewGuid(),UserId=u.Id,DepartmentId=r.DepartmentId,StudentNumber=r.StudentNumber,EntryYear=r.EntryYear,GPA=r.GPA,Status=r.Status,User=u};db.Users.Add(u);db.Students.Add(s);await db.SaveChangesAsync(ct);var d=await db.Departments.FindAsync([r.DepartmentId],ct);return new(s.Id,r.FullName,r.StudentNumber,d?.Name??"",d?.DegreeLevel??"",r.GPA,r.Status);}
public async Task DeleteStudentAsync(Guid id,CancellationToken ct){var s=await db.Students.Include(x=>x.User).SingleOrDefaultAsync(x=>x.Id==id,ct)??throw new KeyNotFoundException();db.Students.Remove(s);db.Users.Remove(s.User);await db.SaveChangesAsync(ct);}
public async Task<IReadOnlyList<TeacherDto>> TeachersAsync(string? s,Guid? d,CancellationToken ct){var q=db.Teachers.AsNoTracking().Include(x=>x.User).Include(x=>x.Department).AsQueryable();if(!string.IsNullOrWhiteSpace(s))q=q.Where(x=>x.User.FullName.Contains(s)||x.Specialty.Contains(s));if(d.HasValue)q=q.Where(x=>x.DepartmentId==d);return await q.Select(x=>new TeacherDto(x.Id,x.User.FullName,x.Department.Name,x.Specialty,x.Status)).ToListAsync(ct);}
public async Task<TeacherDto> CreateTeacherAsync(CreateTeacherRequest r,CancellationToken ct){var u=new User{Id=Guid.NewGuid(),Username=r.Username,PasswordHash=BCrypt.Net.BCrypt.HashPassword(r.Password),FullName=r.FullName,Email=r.Email,Role=UserRole.Teacher,CreatedAt=DateTime.UtcNow};var t=new Teacher{Id=Guid.NewGuid(),UserId=u.Id,DepartmentId=r.DepartmentId,Specialty=r.Specialty,Status=r.Status,User=u};db.Users.Add(u);db.Teachers.Add(t);await db.SaveChangesAsync(ct);var d=await db.Departments.FindAsync([r.DepartmentId],ct);return new(t.Id,r.FullName,d?.Name??"",r.Specialty,r.Status);}
public async Task<IReadOnlyList<DepartmentDto>> DepartmentsAsync(CancellationToken ct)=>await db.Departments.AsNoTracking().Select(d=>new DepartmentDto(d.Id,d.Name,d.ManagerName,d.DegreeLevel,d.IsActive,d.Students.Count,d.Teachers.Count)).ToListAsync(ct);
public async Task<DepartmentDto> CreateDepartmentAsync(CreateDepartmentRequest r,CancellationToken ct){var d=new Department{Id=Guid.NewGuid(),Name=r.Name,ManagerName=r.ManagerName,DegreeLevel=r.DegreeLevel};db.Departments.Add(d);await db.SaveChangesAsync(ct);return new(d.Id,d.Name,d.ManagerName,d.DegreeLevel,true,0,0);}
public async Task DeleteDepartmentAsync(Guid id,CancellationToken ct){var d=await db.Departments.FindAsync([id],ct)??throw new KeyNotFoundException();db.Departments.Remove(d);await db.SaveChangesAsync(ct);}
public async Task<IReadOnlyList<QuestionDto>> QuestionsAsync(Guid? d,CancellationToken ct){var q=db.Questions.AsNoTracking().Include(x=>x.Department).Include(x=>x.CreatedByTeacher).ThenInclude(x=>x.User).Include(x=>x.Options).AsQueryable();if(d.HasValue)q=q.Where(x=>x.DepartmentId==d);return await q.Select(x=>new QuestionDto(x.Id,x.Text,x.Type,x.Points,x.Department.Name,x.CreatedByTeacher.User.FullName,x.Options.Select(o=>new QuestionOptionDto(o.Id,o.Text,o.IsCorrect)).ToList())).ToListAsync(ct);}
public async Task<QuestionDto> CreateQuestionAsync(CreateQuestionRequest r,CancellationToken ct){var q=new Question{Id=Guid.NewGuid(),DepartmentId=r.DepartmentId,CreatedByTeacherId=r.TeacherId,Text=r.Text,Type=r.Type,Points=r.Points,Options=r.Options.Select(o=>new QuestionOption{Id=Guid.NewGuid(),Text=o.Text,IsCorrect=o.IsCorrect}).ToList()};db.Questions.Add(q);await db.SaveChangesAsync(ct);var x=await db.Questions.Include(a=>a.Department).Include(a=>a.CreatedByTeacher).ThenInclude(a=>a.User).Include(a=>a.Options).SingleAsync(a=>a.Id==q.Id,ct);return new(x.Id,x.Text,x.Type,x.Points,x.Department.Name,x.CreatedByTeacher.User.FullName,x.Options.Select(o=>new QuestionOptionDto(o.Id,o.Text,o.IsCorrect)).ToList());}
public async Task<IReadOnlyList<ExamDto>> ExamsAsync(CancellationToken ct)=>await db.Exams.AsNoTracking().Include(x=>x.Department).Include(x=>x.Teacher).ThenInclude(x=>x.User).Select(x=>new ExamDto(x.Id,x.Title,x.Department.Name,x.Teacher.User.FullName,x.DurationMinutes,x.PassingScore,x.ScheduledAt,x.Status,x.Questions.Count)).ToListAsync(ct);
public async Task<ExamDto> CreateExamAsync(CreateExamRequest r,CancellationToken ct){var e=new Exam{Id=Guid.NewGuid(),DepartmentId=r.DepartmentId,TeacherId=r.TeacherId,Title=r.Title,DurationMinutes=r.DurationMinutes,PassingScore=r.PassingScore,ScheduledAt=r.ScheduledAt,AllowNavigation=r.AllowNavigation,Status=ExamStatus.Published};e.Questions=r.QuestionIds.Select((id,i)=>new ExamQuestion{ExamId=e.Id,QuestionId=id,SortOrder=i+1}).ToList();db.Exams.Add(e);await db.SaveChangesAsync(ct);return (await ExamsAsync(ct)).First(x=>x.Id==e.Id);}
public async Task<object> DashboardAsync(CancellationToken ct)=>new{students=await db.Students.CountAsync(ct),teachers=await db.Teachers.CountAsync(ct),departments=await db.Departments.CountAsync(ct),questions=await db.Questions.CountAsync(ct),exams=await db.Exams.CountAsync(ct)};
}