IF DB_ID(N'MftDb') IS NULL CREATE DATABASE MftDb;
GO
USE MftDb;
GO
CREATE TABLE Users(Id uniqueidentifier NOT NULL PRIMARY KEY,Username nvarchar(100) NOT NULL UNIQUE,PasswordHash nvarchar(255) NOT NULL,Role nvarchar(30) NOT NULL,FullName nvarchar(200) NOT NULL,Email nvarchar(200) NOT NULL,Mobile nvarchar(30) NOT NULL DEFAULT N'',MustChangePassword bit NOT NULL DEFAULT 0,DepartmentId uniqueidentifier NULL,IsActive bit NOT NULL DEFAULT 1,CreatedAt datetime2 NOT NULL DEFAULT sysutcdatetime());
CREATE TABLE Departments(Id uniqueidentifier NOT NULL PRIMARY KEY,Name nvarchar(200) NOT NULL,ManagerName nvarchar(200) NULL,DegreeLevel nvarchar(100) NOT NULL,IsActive bit NOT NULL DEFAULT 1);
ALTER TABLE Users ADD CONSTRAINT FK_Users_Department FOREIGN KEY(DepartmentId) REFERENCES Departments(Id) ON DELETE NO ACTION;
CREATE TABLE Students(Id uniqueidentifier NOT NULL PRIMARY KEY,UserId uniqueidentifier NOT NULL UNIQUE,DepartmentId uniqueidentifier NOT NULL,StudentNumber nvarchar(50) NOT NULL UNIQUE,EntryYear nvarchar(10) NOT NULL,GPA decimal(4,2) NULL,Status nvarchar(50) NOT NULL,FOREIGN KEY(UserId) REFERENCES Users(Id) ON DELETE CASCADE,FOREIGN KEY(DepartmentId) REFERENCES Departments(Id));
CREATE TABLE Teachers(Id uniqueidentifier NOT NULL PRIMARY KEY,UserId uniqueidentifier NOT NULL UNIQUE,DepartmentId uniqueidentifier NOT NULL,Specialty nvarchar(200) NOT NULL,Status nvarchar(50) NOT NULL,FOREIGN KEY(UserId) REFERENCES Users(Id) ON DELETE CASCADE,FOREIGN KEY(DepartmentId) REFERENCES Departments(Id));
CREATE TABLE Questions(Id uniqueidentifier NOT NULL PRIMARY KEY,DepartmentId uniqueidentifier NOT NULL,CreatedByTeacherId uniqueidentifier NOT NULL,Type nvarchar(30) NOT NULL,Text nvarchar(max) NOT NULL,Points decimal(8,2) NOT NULL DEFAULT 1,IsActive bit NOT NULL DEFAULT 1,FOREIGN KEY(DepartmentId) REFERENCES Departments(Id),FOREIGN KEY(CreatedByTeacherId) REFERENCES Teachers(Id));
CREATE TABLE QuestionOptions(Id uniqueidentifier NOT NULL PRIMARY KEY,QuestionId uniqueidentifier NOT NULL,Text nvarchar(1000) NOT NULL,IsCorrect bit NOT NULL DEFAULT 0,FOREIGN KEY(QuestionId) REFERENCES Questions(Id) ON DELETE CASCADE);
CREATE TABLE Exams(Id uniqueidentifier NOT NULL PRIMARY KEY,DepartmentId uniqueidentifier NOT NULL,TeacherId uniqueidentifier NOT NULL,Title nvarchar(250) NOT NULL,DurationMinutes int NOT NULL,PassingScore decimal(5,2) NOT NULL,ScheduledAt datetime2 NOT NULL,AllowNavigation bit NOT NULL,Status nvarchar(30) NOT NULL,FOREIGN KEY(DepartmentId) REFERENCES Departments(Id),FOREIGN KEY(TeacherId) REFERENCES Teachers(Id));
CREATE TABLE ExamQuestions(ExamId uniqueidentifier NOT NULL,QuestionId uniqueidentifier NOT NULL,SortOrder int NOT NULL,PRIMARY KEY(ExamId,QuestionId),FOREIGN KEY(ExamId) REFERENCES Exams(Id) ON DELETE CASCADE,FOREIGN KEY(QuestionId) REFERENCES Questions(Id));
CREATE TABLE ExamAttempts(Id uniqueidentifier NOT NULL PRIMARY KEY,ExamId uniqueidentifier NOT NULL,StudentId uniqueidentifier NOT NULL,StartedAt datetime2 NOT NULL,SubmittedAt datetime2 NULL,Score decimal(8,2) NULL,FOREIGN KEY(ExamId) REFERENCES Exams(Id),FOREIGN KEY(StudentId) REFERENCES Students(Id));
CREATE TABLE ExamAnswers(Id uniqueidentifier NOT NULL PRIMARY KEY,AttemptId uniqueidentifier NOT NULL,QuestionId uniqueidentifier NOT NULL,SelectedOptionId uniqueidentifier NULL,EssayText nvarchar(max) NULL,Score decimal(8,2) NULL,FOREIGN KEY(AttemptId) REFERENCES ExamAttempts(Id) ON DELETE CASCADE);
CREATE TABLE Notifications(Id uniqueidentifier NOT NULL PRIMARY KEY,UserId uniqueidentifier NOT NULL,Title nvarchar(250) NOT NULL,Message nvarchar(max) NOT NULL,IsRead bit NOT NULL DEFAULT 0,CreatedAt datetime2 NOT NULL DEFAULT sysutcdatetime(),FOREIGN KEY(UserId) REFERENCES Users(Id));
CREATE INDEX IX_Users_DepartmentId ON Users(DepartmentId); CREATE INDEX IX_Students_DepartmentId ON Students(DepartmentId); CREATE INDEX IX_Teachers_DepartmentId ON Teachers(DepartmentId); CREATE INDEX IX_Questions_DepartmentId ON Questions(DepartmentId); CREATE INDEX IX_Exams_ScheduledAt ON Exams(ScheduledAt);
GO