using Mft.Application.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Mft.Domain;
using Mft.Infrastructure.Persistence;
namespace Mft.Api.Controllers;
[ApiController][Route("api/manage")][Authorize]
public sealed class ManagementController(AppDbContext db,ICurrentUser current):ControllerBase {
 public sealed record UpdateStudentRequest(string FullName,string Email,string Mobile,string StudentNumber,string EntryYear,decimal? GPA,string Status);
 public sealed record UpdateTeacherRequest(string FullName,string Email,string Mobile,string Specialty,string Status);
 public sealed record UpdateQuestionRequest(string Text,QuestionType Type,decimal Points,bool IsActive);
 public sealed record UpdateExamRequest(string Title,int DurationMinutes,decimal PassingScore,DateTime ScheduledAt,bool AllowNavigation,ExamStatus Status);
 public sealed record GradeAnswerRequest(decimal Score);
 async Task<Guid?> Scope(CancellationToken ct){if(current.Role==UserRole.SuperAdmin)return null;if(current.Role==UserRole.Department)return await db.Users.Where(x=>x.Id==current.UserId).Select(x=>x.DepartmentId).SingleOrDefaultAsync(ct);if(current.Role==UserRole.Teacher)return await db.Teachers.Where(x=>x.UserId==current.UserId).Select(x=>(Guid?)x.DepartmentId).SingleOrDefaultAsync(ct);return await db.Students.Where(x=>x.UserId==current.UserId).Select(x=>(Guid?)x.DepartmentId).SingleOrDefaultAsync(ct);}
 async Task<bool> InScope(Guid departmentId,CancellationToken ct){var scope=await Scope(ct);return !scope.HasValue||scope.Value==departmentId;}
 [Authorize(Roles="SuperAdmin,Department,Teacher")][HttpPut("students/{id:guid}")] public async Task<IActionResult> UpdateStudent(Guid id,UpdateStudentRequest r,CancellationToken ct){var s=await db.Students.Include(x=>x.User).SingleOrDefaultAsync(x=>x.Id==id,ct);if(s is null)return NotFound();if(!await InScope(s.DepartmentId,ct))return Forbid();s.User.FullName=r.FullName;s.User.Email=r.Email;s.User.Mobile=r.Mobile;s.StudentNumber=r.StudentNumber;s.EntryYear=r.EntryYear;s.GPA=r.GPA;s.Status=r.Status;await db.SaveChangesAsync(ct);return NoContent();}
 [Authorize(Roles="SuperAdmin,Department")][HttpPut("teachers/{id:guid}")] public async Task<IActionResult> UpdateTeacher(Guid id,UpdateTeacherRequest r,CancellationToken ct){var t=await db.Teachers.Include(x=>x.User).SingleOrDefaultAsync(x=>x.Id==id,ct);if(t is null)return NotFound();if(!await InScope(t.DepartmentId,ct))return Forbid();t.User.FullName=r.FullName;t.User.Email=r.Email;t.User.Mobile=r.Mobile;t.Specialty=r.Specialty;t.Status=r.Status;await db.SaveChangesAsync(ct);return NoContent();}
 [Authorize(Roles="SuperAdmin")][HttpPatch("users/{id:guid}/active")] public async Task<IActionResult> SetUserActive(Guid id,[FromQuery]bool active,CancellationToken ct){var u=await db.Users.SingleOrDefaultAsync(x=>x.Id==id,ct);if(u is null)return NotFound();if(u.Role==UserRole.SuperAdmin&& !active && await db.Users.CountAsync(x=>x.Role==UserRole.SuperAdmin&&x.IsActive,ct)<=1)return BadRequest(new{message="حداقل یک مدیر سیستم فعال باید باقی بماند."});u.IsActive=active;await db.SaveChangesAsync(ct);return NoContent();}
 [Authorize(Roles="SuperAdmin,Teacher")][HttpPut("questions/{id:guid}")] public async Task<IActionResult> UpdateQuestion(Guid id,UpdateQuestionRequest r,CancellationToken ct){var q=await db.Questions.Include(x=>x.CreatedByTeacher).SingleOrDefaultAsync(x=>x.Id==id,ct);if(q is null)return NotFound();if(current.Role==UserRole.Teacher&&q.CreatedByTeacher.UserId!=current.UserId)return Forbid();q.Text=r.Text;q.Type=r.Type;q.Points=r.Points;q.IsActive=r.IsActive;await db.SaveChangesAsync(ct);return NoContent();}
 [Authorize(Roles="SuperAdmin,Teacher")][HttpDelete("questions/{id:guid}")] public async Task<IActionResult> DeleteQuestion(Guid id,CancellationToken ct){var q=await db.Questions.Include(x=>x.Options).Include(x=>x.ExamQuestions).Include(x=>x.CreatedByTeacher).SingleOrDefaultAsync(x=>x.Id==id,ct);if(q is null)return NotFound();if(current.Role==UserRole.Teacher&&q.CreatedByTeacher.UserId!=current.UserId)return Forbid();if(q.ExamQuestions.Count>0)return Conflict(new{message="سؤال متصل به آزمون است؛ ابتدا ارتباط آزمون را حذف کنید."});db.Questions.Remove(q);await db.SaveChangesAsync(ct);return NoContent();}
 [Authorize(Roles="SuperAdmin,Teacher")][HttpPut("exams/{id:guid}")] public async Task<IActionResult> UpdateExam(Guid id,UpdateExamRequest r,CancellationToken ct){var e=await db.Exams.Include(x=>x.Teacher).SingleOrDefaultAsync(x=>x.Id==id,ct);if(e is null)return NotFound();if(current.Role==UserRole.Teacher&&e.Teacher.UserId!=current.UserId)return Forbid();if(r.DurationMinutes<1)return BadRequest(new{message="مدت آزمون باید بیشتر از صفر باشد."});e.Title=r.Title;e.DurationMinutes=r.DurationMinutes;e.PassingScore=r.PassingScore;e.ScheduledAt=r.ScheduledAt;e.AllowNavigation=r.AllowNavigation;e.Status=r.Status;await db.SaveChangesAsync(ct);return NoContent();}
 [Authorize(Roles="SuperAdmin,Teacher")][HttpDelete("exams/{id:guid}")] public async Task<IActionResult> DeleteExam(Guid id,CancellationToken ct){var e=await db.Exams.Include(x=>x.Teacher).Include(x=>x.Attempts).SingleOrDefaultAsync(x=>x.Id==id,ct);if(e is null)return NotFound();if(current.Role==UserRole.Teacher&&e.Teacher.UserId!=current.UserId)return Forbid();if(e.Attempts.Count>0)return Conflict(new{message="آزمونی که پاسخ‌نامه دارد قابل حذف نیست."});db.Exams.Remove(e);await db.SaveChangesAsync(ct);return NoContent();}
 [Authorize(Roles="SuperAdmin,Teacher")][HttpGet("exams/{id:guid}/attempts")] public async Task<IActionResult> ExamAttempts(Guid id,CancellationToken ct){var e=await db.Exams.Include(x=>x.Teacher).SingleOrDefaultAsync(x=>x.Id==id,ct);if(e is null)return NotFound();if(current.Role==UserRole.Teacher&&e.Teacher.UserId!=current.UserId)return Forbid();return Ok(await db.ExamAttempts.AsNoTracking().Where(x=>x.ExamId==id).Select(x=>new{id=x.Id,student=x.Student.User.FullName,studentNumber=x.Student.StudentNumber,x.StartedAt,x.SubmittedAt,x.Score,answers=x.Answers.Count}).ToListAsync(ct));}
 [Authorize(Roles="SuperAdmin,Teacher")][HttpPut("answers/{id:guid}/grade")] public async Task<IActionResult> GradeAnswer(Guid id,GradeAnswerRequest r,CancellationToken ct){if(r.Score<0)return BadRequest();var a=await db.ExamAnswers.Include(x=>x.Attempt).ThenInclude(x=>x.Exam).ThenInclude(x=>x.Teacher).SingleOrDefaultAsync(x=>x.Id==id,ct);if(a is null)return NotFound();if(current.Role==UserRole.Teacher&&a.Attempt.Exam.Teacher.UserId!=current.UserId)return Forbid();a.Score=r.Score;var answers=await db.ExamAnswers.Where(x=>x.AttemptId==a.AttemptId).ToListAsync(ct);a.Attempt.Score=answers.All(x=>x.Score.HasValue)?answers.Sum(x=>x.Score!.Value):null;await db.SaveChangesAsync(ct);return NoContent();}
}