using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Mft.Api;
using Mft.Domain;
using Mft.Infrastructure.Persistence;
namespace Mft.Api.Controllers;
[ApiController][Route("api/portal")][Authorize]
public sealed class PortalController(AppDbContext db,ICurrentUser current):ControllerBase {
 public sealed record AnswerInput(Guid QuestionId,Guid? SelectedOptionId,string? EssayText);
 public sealed record SubmitAttemptRequest(IReadOnlyList<AnswerInput> Answers);
 [HttpGet("me")] public async Task<IActionResult> Me(CancellationToken ct){var u=await db.Users.AsNoTracking().Where(x=>x.Id==current.UserId).Select(x=>new{ x.Id,x.Username,x.FullName,x.Email,x.Mobile,Role=x.Role.ToString(),x.MustChangePassword,x.DepartmentId}).SingleOrDefaultAsync(ct);return u is null?NotFound():Ok(u);}
 [Authorize(Roles="Student")][HttpGet("my-exams")] public async Task<IActionResult> MyExams(CancellationToken ct){var student=await db.Students.SingleOrDefaultAsync(x=>x.UserId==current.UserId,ct);if(student is null)return NotFound();var now=DateTime.UtcNow;var exams=await db.Exams.AsNoTracking().Where(x=>x.DepartmentId==student.DepartmentId&&x.Status==ExamStatus.Published&&x.ScheduledAt<=now).Select(x=>new{id=x.Id,title=x.Title,x.DurationMinutes,x.PassingScore,x.ScheduledAt,questionCount=x.Questions.Count,attempted=x.Attempts.Any(a=>a.StudentId==student.Id&&a.SubmittedAt!=null)}).ToListAsync(ct);return Ok(exams);}
 [Authorize(Roles="Student")][HttpPost("exams/{examId:guid}/start")] public async Task<IActionResult> StartExam(Guid examId,CancellationToken ct){var student=await db.Students.SingleOrDefaultAsync(x=>x.UserId==current.UserId,ct);if(student is null)return NotFound();var exam=await db.Exams.SingleOrDefaultAsync(x=>x.Id==examId&&x.DepartmentId==student.DepartmentId&&x.Status==ExamStatus.Published&&x.ScheduledAt<=DateTime.UtcNow,ct);if(exam is null)return NotFound();if(await db.ExamAttempts.AnyAsync(x=>x.StudentId==student.Id&&x.ExamId==examId&&x.SubmittedAt!=null,ct))return Conflict(new{message="این آزمون قبلاً ثبت نهایی شده است."});var attempt=new ExamAttempt{Id=Guid.NewGuid(),ExamId=examId,StudentId=student.Id,StartedAt=DateTime.UtcNow};db.ExamAttempts.Add(attempt);await db.SaveChangesAsync(ct);var questions=await db.ExamQuestions.Where(x=>x.ExamId==examId).OrderBy(x=>x.SortOrder).Select(x=>new{id=x.QuestionId,text=x.Question.Text,type=x.Question.Type.ToString(),x.Question.Points,options=x.Question.Options.Select(o=>new{id=o.Id,text=o.Text})}).ToListAsync(ct);return Ok(new{attemptId=attempt.Id,exam.Title,exam.DurationMinutes,startedAt=attempt.StartedAt,questions});}
 [Authorize(Roles="Student")][HttpPost("attempts/{attemptId:guid}/submit")] public async Task<IActionResult> Submit(Guid attemptId,SubmitAttemptRequest request,CancellationToken ct){var student=await db.Students.SingleOrDefaultAsync(x=>x.UserId==current.UserId,ct);if(student is null)return NotFound();var attempt=await db.ExamAttempts.Include(x=>x.Exam).SingleOrDefaultAsync(x=>x.Id==attemptId&&x.StudentId==student.Id,ct);if(attempt is null)return NotFound();if(attempt.SubmittedAt is not null)return Conflict(new{message="این پاسخ‌نامه قبلاً ثبت شده است."});if(DateTime.UtcNow>attempt.StartedAt.AddMinutes(attempt.Exam.DurationMinutes))return BadRequest(new{message="زمان آزمون به پایان رسیده است."});var allowed=await db.ExamQuestions.Where(x=>x.ExamId==attempt.ExamId).Select(x=>x.QuestionId).ToListAsync(ct);foreach(var a in request.Answers){if(!allowed.Contains(a.QuestionId))return BadRequest(new{message="سؤال نامعتبر است."});if(a.SelectedOptionId.HasValue&&!await db.QuestionOptions.AnyAsync(x=>x.Id==a.SelectedOptionId&&x.QuestionId==a.QuestionId,ct))return BadRequest(new{message="گزینه انتخاب‌شده نامعتبر است."});db.ExamAnswers.Add(new ExamAnswer{Id=Guid.NewGuid(),AttemptId=attempt.Id,QuestionId=a.QuestionId,SelectedOptionId=a.SelectedOptionId,EssayText=a.EssayText});}attempt.SubmittedAt=DateTime.UtcNow;await db.SaveChangesAsync(ct);return Ok(new{attempt.Id,attempt.SubmittedAt,message="پاسخ‌نامه ثبت شد."});}
 [Authorize(Roles="Student")][HttpGet("my-attempts")] public async Task<IActionResult> MyAttempts(CancellationToken ct){var student=await db.Students.SingleOrDefaultAsync(x=>x.UserId==current.UserId,ct);if(student is null)return NotFound();return Ok(await db.ExamAttempts.AsNoTracking().Where(x=>x.StudentId==student.Id).OrderByDescending(x=>x.StartedAt).Select(x=>new{id=x.Id,examTitle=x.Exam.Title,x.StartedAt,x.SubmittedAt,x.Score}).ToListAsync(ct));}
 [HttpGet("notifications")] public async Task<IActionResult> Notifications(CancellationToken ct)=>Ok(await db.Notifications.AsNoTracking().Where(x=>x.UserId==current.UserId).OrderByDescending(x=>x.CreatedAt).Select(x=>new{x.Id,x.Title,x.Message,x.IsRead,x.CreatedAt}).ToListAsync(ct));
 [HttpPost("notifications/{id:guid}/read")] public async Task<IActionResult> MarkRead(Guid id,CancellationToken ct){var n=await db.Notifications.SingleOrDefaultAsync(x=>x.Id==id&&x.UserId==current.UserId,ct);if(n is null)return NotFound();n.IsRead=true;await db.SaveChangesAsync(ct);return NoContent();}
}