namespace Mft.Domain;
public enum UserRole { Student, Teacher, Department, SuperAdmin }
public enum QuestionType { MultipleChoice, Essay }
public enum ExamStatus { Draft, Published, Closed }
public sealed class User {
 public Guid Id {get;set;} public string Username {get;set;}="" ; public string PasswordHash {get;set;}="";
 public UserRole Role {get;set;} public string FullName {get;set;}="" ; public string Email {get;set;}="";
 public string Mobile {get;set;}="" ; public bool MustChangePassword {get;set;} public bool IsActive {get;set;}=true;
 public Guid? DepartmentId {get;set;} public Student? Student {get;set;} public Teacher? Teacher {get;set;} public DateTime CreatedAt {get;set;}
}
public sealed class Department { public Guid Id {get;set;} public string Name {get;set;}="" ; public string? ManagerName {get;set;} public string DegreeLevel {get;set;}="" ; public bool IsActive {get;set;}=true; public ICollection<Student> Students {get;set;}=[]; public ICollection<Teacher> Teachers {get;set;}=[]; public ICollection<Exam> Exams {get;set;}=[]; }
public sealed class Student { public Guid Id {get;set;} public Guid UserId {get;set;} public Guid DepartmentId {get;set;} public string StudentNumber {get;set;}="" ; public string EntryYear {get;set;}="" ; public decimal? GPA {get;set;} public string Status {get;set;}="Active"; public User User {get;set;}=null!; public Department Department {get;set;}=null!; public ICollection<ExamAttempt> Attempts {get;set;}=[]; }
public sealed class Teacher { public Guid Id {get;set;} public Guid UserId {get;set;} public Guid DepartmentId {get;set;} public string Specialty {get;set;}="" ; public string Status {get;set;}="Active"; public User User {get;set;}=null!; public Department Department {get;set;}=null!; public ICollection<Exam> Exams {get;set;}=[]; }
public sealed class Question { public Guid Id {get;set;} public Guid DepartmentId {get;set;} public Guid CreatedByTeacherId {get;set;} public QuestionType Type {get;set;} public string Text {get;set;}="" ; public decimal Points {get;set;}=1; public bool IsActive {get;set;}=true; public Department Department {get;set;}=null!; public Teacher CreatedByTeacher {get;set;}=null!; public ICollection<QuestionOption> Options {get;set;}=[]; public ICollection<ExamQuestion> ExamQuestions {get;set;}=[]; }
public sealed class QuestionOption { public Guid Id {get;set;} public Guid QuestionId {get;set;} public string Text {get;set;}="" ; public bool IsCorrect {get;set;} public Question Question {get;set;}=null!; }
public sealed class Exam { public Guid Id {get;set;} public Guid DepartmentId {get;set;} public Guid TeacherId {get;set;} public string Title {get;set;}="" ; public int DurationMinutes {get;set;} public decimal PassingScore {get;set;} public DateTime ScheduledAt {get;set;} public bool AllowNavigation {get;set;} public ExamStatus Status {get;set;}=ExamStatus.Draft; public Department Department {get;set;}=null!; public Teacher Teacher {get;set;}=null!; public ICollection<ExamQuestion> Questions {get;set;}=[]; public ICollection<ExamAttempt> Attempts {get;set;}=[]; }
public sealed class ExamQuestion { public Guid ExamId {get;set;} public Guid QuestionId {get;set;} public int SortOrder {get;set;} public Exam Exam {get;set;}=null!; public Question Question {get;set;}=null!; }
public sealed class ExamAttempt { public Guid Id {get;set;} public Guid ExamId {get;set;} public Guid StudentId {get;set;} public DateTime StartedAt {get;set;} public DateTime? SubmittedAt {get;set;} public decimal? Score {get;set;} public Exam Exam {get;set;}=null!; public Student Student {get;set;}=null!; public ICollection<ExamAnswer> Answers {get;set;}=[]; }
public sealed class ExamAnswer { public Guid Id {get;set;} public Guid AttemptId {get;set;} public Guid QuestionId {get;set;} public Guid? SelectedOptionId {get;set;} public string? EssayText {get;set;} public decimal? Score {get;set;} public ExamAttempt Attempt {get;set;}=null!; }
public sealed class Notification { public Guid Id {get;set;} public Guid UserId {get;set;} public string Title {get;set;}="" ; public string Message {get;set;}="" ; public bool IsRead {get;set;} public DateTime CreatedAt {get;set;} }
